library identifier: 'jenkins-pipeline-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/ljupcokostic/jenkins-pipeline-library.git'])

crossPlatformBuild repoName: 'ljupchokostic/jenkins',
                   linuxContext: 'm4', 
                   windowsContext: 'm4'
